import type { Metadata } from "next";
import { Big_Shoulders_Display } from "next/font/google";
import "./globals.css";

const BSD = Big_Shoulders_Display({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Siraphop ✦ Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BSD.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
